In [ ]:
import qutip.testing as qt
qt.run()


QuTiP: Quantum Toolbox in Python
Copyright (c) 2011 and later.
A. J. Pitchford, P. D. Nation, R. J. Johansson, A. Grimsmo, and C. Granade

QuTiP Version:      4.3.1
Numpy Version:      1.15.3
Scipy Version:      1.1.0
Cython Version:     0.29
Matplotlib Version: 3.0.0
Python Version:     3.6.6
Number of CPUs:     2
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Linux (x86_64)
Installation path:  /home/rmk/anaconda3/lib/python3.6/site-packages/qutip
Please cite QuTiP in your publication.
For your convenience a bibtex file can be easily generated using `qutip.cite()`


DEBUG:qutip.logging_utils:Creating logger for qutip.control.grape with policy basic.
DEBUG:qutip.logging_utils:Creating logger for qutip.control.optimconfig with policy basic.
DEBUG:qutip.logging_utils:Creating logger for qutip.control.dynamics with policy basic.
DEBUG:qutip.logging_utils:Creating logger for qutip.control.dump with policy basic.
DEBUG:qutip.logging_utils:Creating logger for qutip.control.tslotcomp with policy basic.
DEBUG:qutip.logging_utils:Creating logger for qutip.control.fidcomp with policy basic.
DEBUG:qutip.logging_utils:Creating logger for qutip.control.propcomp with policy basic.
DEBUG:qutip.logging_utils:Creating logger for qutip.control.optimizer with policy basic.
DEBUG:qutip.logging_utils:Creating logger for qutip.control.pulsegen with policy basic.
DEBUG:qutip.logging_utils:Creating logger for qutip.control.loadparams with policy basic.
DEBUG:qutip.logging_utils:Creating logger for qutip.control.pulseoptim with policy basic.
Transform 2-level to eigenbasis

Interpolate: mesolve str + interp (real) ... /home/rmk/anaconda3/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/rmk/Python Codes/rhs245924.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
ERROR
Interpolate: mesolve func + interp (real) ... /home/rmk/anaconda3/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/rmk/Python Codes/rhs245925.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
ERROR
Interpolate: mcsolve str + interp (real) ... /home/rmk/anaconda3/lib/python3.6/site-packages/qutip/mcsolve.py:1152: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.from_iter(generator)) or the python sum builtin instead.
  H = np.array([np.su

# 1.Intro to QuTip

## 1.1Basic Operators:

In [ ]:
from qutip import *
a=basis(5,0)
print("Basis ket= ",a)

print("Identity matrix= \n",qeye(3))

print("Lowering (Annihilation) operator= \n", destroy(3))
print("Raising (Creation) operator= \n", create(3))

print("Number operator= \n",num(3))

print("Momentum operator= \n",momentum(3))
print("Position operator= \n",position(4))


## 1.2Basic Computations(1D)-

In [ ]:
from qutip import *
import numpy as np

#Basic 

A=Qobj([[1],[0],[-1]])
print(A)
print("Norm of A= ",A.norm())
print("Transpose= ",A.trans())
print("A*I= \n",A.trans()*qeye(3))

B=Qobj([[1],[-5j],[-2],[4j]])
print(B)
print("Dagger(complex conjugate transpose) of B= ",B.dag())
print("Conjugate of B= ",B.conj())

#Creation and Annihilation Operator

print("Lowering (Annihilation) operator= \n", destroy(3))
print("Annihilation on A=\n", A.trans()*destroy(3))
print("Raising (Creation) operator= \n", create(3))
print("Creation on A=\n", A.trans()*create(3))

#Position,Momentum,Number Operator

print("Position on A= \n",A.trans()*position(3))
print("Momentum on A= \n",A.trans()*momentum(3))
print("Number operator= ",A.trans()*num(3))




## 1.3Basic Computations(2D)-

In [ ]:
from qutip import *
import numpy as np

#Matrix representation of Qobj
X=np.matrix('1,2,1;0,2,1;0,1,-1j')                    #or np.matrix([[1,2,1],[0,2,1]]) 
print(Qobj(X))
Y=np.random.rand(3,2)
print(Qobj(Y))

## 1.4EigenValues and Eigenvectors-

In [267]:
from qutip import *
import numpy as np
M=Qobj(np.matrix('2,1,0;1,2,1;0,1,2'))
print(type(M))
print("Matrix M= ",M)
EVAL,EVEC=M.eigenstates()
print("Eigenvalues are= ",EVAL)
print("Eigenvectors= \n",EVEC)


<class 'qutip.qobj.Qobj'>
Matrix M=  Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[2. 1. 0.]
 [1. 2. 1.]
 [0. 1. 2.]]
Eigenvalues are=  [0.58578644 2.         3.41421356]
Eigenvectors= 
 [Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[ 0.5       ]
 [-0.70710678]
 [ 0.5       ]]
 Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[-0.70710678]
 [ 0.        ]
 [ 0.70710678]]
 Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[0.5       ]
 [0.70710678]
 [0.5       ]]]


## 2.Simple Harmonic Oscillator

## 2.1 Numerical

In [121]:
from qutip import *
import numpy as np
s0=ket([0],4)
s0

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

In [122]:
adag=create(4)
adag

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.        ]
 [1.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.        ]
 [0.         0.         1.73205081 0.        ]]

In [188]:
adag**2*s0
print("Number operator= ",adag*destroy(4))

Number operator=  Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 3.]]


In [161]:
H=adag*destroy(4) + 0.5*qeye(4)
H

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.5 0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  2.5 0. ]
 [0.  0.  0.  3.5]]

In [176]:
#Normalized eigenstate
from math import *
from qutip import *
import numpy as np

s0=ket([0],4)
print(s0)
adag=create(4)
def psi(n):

    Psi=((adag**n)*s0)/sqrt(math.factorial(n))    #sqrt(math.factorial(n))
    return Psi
n=int(input("Enter no. of states= "))
for i in range(0,n):
    print("Psi_",i,"= ",psi(i))

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]
Enter no. of states= 4
Psi_ 0 =  Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]
Psi_ 1 =  Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]
Psi_ 2 =  Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]
Psi_ 3 =  Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]]


$$ a_{+}\psi_{n} $$

In [194]:
def cr_psi(n):
    Val=psi(n+1)*sqrt(n+1)
    return Val
print("Ground state= ",s0)
print("a{+} Psi(0)= ",cr_psi(0))

Ground state=  Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]
a{+} Psi(0)=  Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]


$$ a_{-}\psi_{n} $$

In [195]:
def des_psi(n):
    Val=psi(n-1)*sqrt(n)
    return Val
print("Ground state= ",s0)
print("a{-} Psi(0)= ",des_psi(3))


Ground state=  Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]
a{-} Psi(0)=  Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [1.73205081]
 [0.        ]]


## Hamiltonian

In [178]:
#Hamiltonian
def Hamilt(n):
    adag=create(n)
    H=adag*destroy(n) + 0.5*qeye(n)
    return H
Hamilt(4)
s0=ket([0],4)
print(s0)
adag=create(4)
def psi(n):

    Psi=((adag**n)*s0)/sqrt(math.factorial(n))    #sqrt(math.factorial(n))
    return Psi
n=int(input("Enter the no. of states= "))
for i in range (0,n):
    print("Hamiltonian of ",i,"state= ",Hamilt(4)*psi(i))

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]
Enter the no. of states= 4
Hamiltonian of  0 state=  Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.5]
 [0. ]
 [0. ]
 [0. ]]
Hamiltonian of  1 state=  Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0. ]
 [1.5]
 [0. ]
 [0. ]]
Hamiltonian of  2 state=  Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0. ]
 [0. ]
 [2.5]
 [0. ]]
Hamiltonian of  3 state=  Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0. ]
 [0. ]
 [0. ]
 [3.5]]


## 2.Symbolic

In [345]:
from sympy import *
from qutip import *
from matplotlib import rc
import numpy as np
#x,y,psi,phi,omega=symbols('x y \u03C8 \u03C6')
#\mathcal{A}\/\sin(2 \omega t)
m=Symbol('m')
x=Symbol('x')
psi,phi,w,h=symbols(r'\psi \phi \omega \hbar')
exp((-m*psi*x**2)/(2*h))
m=Matrix([[2,m,0],[w,5,2],[0,0,psi]])
                                      #M=Qobj(np.matrix([[2,psi,0],[1,phi,1],[0,1,w]])) 

                                      #m=np.matrix([[2,m,0],[1,5,w],[0,1,2]])  -NOT POSSIBLE IN NUMPY-NO SYMBOL
print(type(m)) 


#M=Qobj(np.matrix([[2,3,0],[1,5,1],[0,1,2]]))
M=Qobj(m)
print(type(M))

print(M)

NameError: name 'sp' is not defined